version: "3.8"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/stacks/sonarr/config:/config
      - /home/eoghan/cachecow:/tv
      - /home/eoghan/cachecow/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks: {}
