version: "3.8"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/stacks/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
networks: {}
