version: "3.8"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0 #
    container_name: mealie
    ports:
      - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - /opt/mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.1.17
    restart: always
networks: {}
