version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /opt/stacks/plex/config:/config
      - /home/eoghan/cachecow:/tv
      - /home/eoghan/cachecow:/movies
    restart: always
networks:
  tautulli_default:
    external: true
