version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/stacks/radarr/config:/config
      - /home/eoghan/cachecow:/movies
      - /home/eoghan/cachecow/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
networks: {}
