services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: homelab
    volumes:
      - .opt/stacks/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  metabase_default:
    external: true
